# Generated by Django 3.0.4 on 2020-03-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='severity',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Moderate'), (3, 'Medium'), (4, 'High'), (5, 'Very High')], default=1),
        ),
    ]
