# Generated by Django 3.0.4 on 2020-03-22 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resourceManager', '0002_patient_severity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='patient',
        ),
        migrations.CreateModel(
            name='MachineAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resourceManager.Machine')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resourceManager.Patient')),
            ],
        ),
    ]
