# Generated by Django 3.0.4 on 2020-03-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceManager', '0003_auto_20200322_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='name',
            new_name='location',
        ),
        migrations.AddField(
            model_name='machine',
            name='model',
            field=models.CharField(default='maquina0', max_length=200),
            preserve_default=False,
        ),
    ]
