# Generated by Django 3.0.4 on 2020-03-26 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resourceManager', '0004_auto_20200322_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineassignment',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_assignments', to='resourceManager.Machine'),
        ),
        migrations.AlterField(
            model_name='machineassignment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_assignments', to='resourceManager.Patient'),
        ),
    ]
