# Generated by Django 3.0.3 on 2020-03-25 23:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('severity', models.IntegerField(choices=[(1, 'Low'), (2, 'Moderate'), (3, 'Medium'), (4, 'High'), (5, 'Very High')], default=1)),
                ('admission_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Admission date: ')),
                ('description', models.TextField(blank=True)),
                ('machine_id', models.IntegerField(default=0)),
                ('history_severity_x', models.TextField(blank=True)),
                ('history_severity_y', models.TextField(blank=True)),
                ('history_machine_x', models.TextField(blank=True)),
                ('history_machine_y', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.MachineType')),
            ],
        ),
    ]
