# Generated by Django 3.0.4 on 2020-03-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='default_pass',
            field=models.CharField(default='patata', editable=False, max_length=20),
            preserve_default=False,
        ),
    ]
