# Generated by Django 3.0.3 on 2020-03-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='machine_id',
            new_name='machine_pk',
        ),
        migrations.AlterField(
            model_name='patient',
            name='severity',
            field=models.IntegerField(choices=[(0, 'Healed'), (1, 'Low'), (2, 'Moderate'), (3, 'Medium'), (4, 'High'), (5, 'Very High'), (6, 'Dead')], default=1),
        ),
    ]
