# Generated by Django 3.0.4 on 2020-03-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='permission_message',
            new_name='permission_machine_edit',
        ),
        migrations.AddField(
            model_name='role',
            name='permission_machinetype_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='permission_message_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='permission_task_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='permission_user_edit',
            field=models.BooleanField(default=False),
        ),
    ]
