# Generated by Django 3.0.4 on 2020-03-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_patient_default_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
