# Generated by Django 3.0.3 on 2020-03-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20200326_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='patient_pk',
            field=models.IntegerField(default=0),
        ),
    ]
