# Generated by Django 3.0.4 on 2020-03-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
