# Generated by Django 3.0.4 on 2020-04-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20200409_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
