# Generated by Django 3.0.4 on 2020-03-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_assignmettask'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmettask',
            name='bool_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assignmettask',
            name='bool_install',
            field=models.BooleanField(choices=[(True, 'Install'), (True, 'Remove')], verbose_name='task'),
        ),
    ]
