# Generated by Django 3.0.4 on 2020-03-27 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20200327_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmettask',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Due by:'),
        ),
    ]
