# Generated by Django 3.0.4 on 2020-03-28 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_patient_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='patient_pk',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='machine_pk',
        ),
        migrations.AddField(
            model_name='machine',
            name='patient_assigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.Patient'),
        ),
        migrations.AddField(
            model_name='patient',
            name='machine_assigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.Machine'),
        ),
    ]
