# Generated by Django 3.0.4 on 2020-04-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_patient_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='id1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
