# Generated by Django 3.0.4 on 2020-04-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20200403_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permission_patient_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='permission_patient_see',
            field=models.BooleanField(default=False),
        ),
    ]
