# Generated by Django 3.0.4 on 2020-03-29 00:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20200328_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Task by:')),
                ('bool_completed', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='initial date:')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='end date:')),
                ('bool_install', models.BooleanField(default=False, verbose_name='installed')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_assignments', to='manager.Machine')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_assignments', to='manager.Patient')),
            ],
        ),
        migrations.DeleteModel(
            name='AssignmetTask',
        ),
    ]
