# Generated by Django 3.0.4 on 2020-03-27 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_assignmettask_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmettask',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='end date:'),
        ),
        migrations.AddField(
            model_name='assignmettask',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='initial date:'),
        ),
        migrations.AlterField(
            model_name='assignmettask',
            name='bool_install',
            field=models.BooleanField(default=False, verbose_name='installed'),
        ),
        migrations.AlterField(
            model_name='assignmettask',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Task by:'),
        ),
    ]
