# Generated by Django 3.0.4 on 2020-04-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20200403_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permission_role_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='permission_role_see',
            field=models.BooleanField(default=False),
        ),
    ]
