# Generated by Django 3.0.4 on 2020-04-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_patient_id1'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='bool_connected',
            field=models.BooleanField(default=False),
        ),
    ]
