# Generated by Django 3.0.4 on 2020-03-29 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20200329_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_receiver', to='manager.Patient'),
        ),
    ]
