# Generated by Django 3.0.4 on 2020-04-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20200404_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='permission_location_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='permission_location_see',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='machine',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
