# Generated by Django 3.0.4 on 2020-04-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_machine_bool_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='treatment_plan',
            field=models.TextField(blank=True, default=''),
        ),
    ]
