# Generated by Django 3.0.4 on 2020-03-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20200329_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='history_machine_x',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='history_machine_y',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='history_severity_x',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='history_severity_y',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
