# Generated by Django 3.0.4 on 2020-03-29 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20200329_0148'),
        ('manager', '0006_auto_20200329_0234'),
    ]

    operations = [
    ]
