# Generated by Django 3.0.4 on 2020-03-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20200327_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='name',
            field=models.CharField(default='Nurse', max_length=100),
            preserve_default=False,
        ),
    ]
