# Generated by Django 3.0.4 on 2020-04-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_patient_treatment_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='treatment_plan',
            field=models.TextField(null=True),
        ),
    ]
