# Generated by Django 3.0.4 on 2020-03-29 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20200329_0304'),
        ('manager', '0007_auto_20200329_1252'),
    ]

    operations = [
    ]
