# Generated by Django 3.0.4 on 2020-03-29 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_merge_20200329_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Patient'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
